<?php
namespace Mageplaza\Vendor\Model\ResourceModel;


class Vendor extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{

    public function __construct(
        \Magento\Framework\Model\ResourceModel\Db\Context $context
    )
    {
        parent::__construct($context);
    }

    protected function _construct()
    {
        $this->_init('vendor', 'vendor_id');
    }

    /*
    protected function _beforeSave(\Magento\Framework\Model\AbstractModel $object)
    {

        // TODO: Change the autogenerated stub
        $object->set


        return parent::_beforeSave($object);
    }
    */

}
